!SESSION 2018-10-30 02:48:03.673 -----------------------------------------------
eclipse.buildId=4.8.0.I20180611-0500
java.version=1.8.0_144
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product

This is a continuation of log file G:\Photon_Automation\.metadata\.bak_0.log
Created Time: 2018-10-30 02:50:20.919

!ENTRY org.eclipse.m2e.logback.appender 2 0 2018-10-30 02:50:20.920
!MESSAGE Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!

!ENTRY org.eclipse.m2e.logback.appender 2 0 2018-10-30 02:50:20.952
!MESSAGE Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!

!ENTRY org.eclipse.m2e.logback.appender 2 0 2018-10-30 02:50:28.336
!MESSAGE Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!

!ENTRY org.eclipse.m2e.logback.appender 2 0 2018-10-30 02:50:28.345
!MESSAGE Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!

!ENTRY org.python.pydev.shared_core 4 4 2018-10-30 02:50:40.045
!MESSAGE java.io.IOException: Cannot run program "C:\Users\Mahesh\AppData\Local\Programs\Python\Python37-32\python.exe": CreateProcess error=2, The system cannot find the file specified
!STACK 0
java.lang.RuntimeException: java.io.IOException: Cannot run program "C:\Users\Mahesh\AppData\Local\Programs\Python\Python37-32\python.exe": CreateProcess error=2, The system cannot find the file specified
	at org.python.pydev.ast.runners.SimpleRunner.run(SimpleRunner.java:314)
	at org.python.pydev.ast.runners.SimpleRunner.run(SimpleRunner.java:280)
	at org.python.pydev.ast.runners.SimpleRunner.runAndGetOutput(SimpleRunner.java:331)
	at org.python.pydev.ast.runners.SimplePythonRunner.runAndGetOutputWithInterpreter(SimplePythonRunner.java:91)
	at org.python.pydev.ast.interpreter_managers.PythonInterpreterManager.doCreateInterpreterInfo(PythonInterpreterManager.java:67)
	at org.python.pydev.ast.interpreter_managers.PythonInterpreterManager.internalCreateInterpreterInfo(PythonInterpreterManager.java:43)
	at org.python.pydev.ast.interpreter_managers.AbstractInterpreterManager.createInterpreterInfo(AbstractInterpreterManager.java:324)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManager$CreateInterpreterInfoCallback.createInterpreterInfo(SyncSystemModulesManager.java:172)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManager.updateStructures(SyncSystemModulesManager.java:278)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler$SynchJob.run(SyncSystemModulesManagerScheduler.java:234)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
Caused by: java.io.IOException: Cannot run program "C:\Users\Mahesh\AppData\Local\Programs\Python\Python37-32\python.exe": CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:105)
	at org.python.pydev.ast.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.ast.runners.SimpleRunner.run(SimpleRunner.java:312)
	... 10 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 15 more
